name: betaM
favicon: null
layout_spectrum: 1
typography_spectrum: 0.75734
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#307cb7'
    - '#5694c4'
    - '#e5eef6'
    - '#97bddb'
  brandStrength: 0.5313569162972271
  lightness: 0.5358872872311622
  saturation: 0.9438215368427336
  rhythmicContrast: 0.1704315636307001
purpose: []
